# GAMELOG_GENERATION
# GAMELOG_PERCENTILES
# OFF_PERCENTILES_DIFF
# DEF_PERCENTILES_DIFF
# CONFERENCE_STATS
# CONFERENCE_STATS_DEF
# DEMOGRAPHIC_INFO
# FINAL_DF_CONSTRUCTION
# COMPARISON_ONE
# TEAM_COMPARISON_PPP
# COMPARISON_POSS
# TEAM_COMPARISON_POSS

### THE OTHER ML, COMPARISON TYPE SHIT